project3/config/routes.rb
Rails.application.routes.draw do

  # Root is the unauthenticated path
  root 'sessions#unauth'

  # Sessions URL
  get 'sessions/unauth', as: :login
  get 'admin/email'
  get 'admin/scrape'
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout
  post 'users/scrape', as: :scrape # Initiaties commands to start scraping articles form web
  post 'users/email', as: :email

  get '/interests', to: 'articles#my_interests', as: 'interests' # Shows articles that have been tagged with interests

  get '/article_search', to: 'articles#article_search', as: 'article_search' # Shows articles that match search result

  resources :users, only: [:create, :new, :update, :destroy, :edit]
  resources :articles, only: [:destroy, :show, :index]


end

project3/app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">The Digest!</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">

          <li><%= link_to "Articles", articles_path%></li>

          <li><%= link_to "Interests", interests_path %></li>

          <li><%= link_to "Scrape Articles", scrape_path, method: :scrape%></li>
          <li><%= link_to "Email Articles", email_path, method: :email%></li>
        </ul>
          <%# Following code attributed to Remi Delhaye 25 October 2015 found at %>
          <%# http://stackoverflow.com/questions/31029976/how-do-i-connect-my-rails-search-form-with-the-bootstrap-search-design%>
          <div class="navbar-form navbar-right">
            <%= form_tag "/article_search", :method => 'get', class: 'input-group'  do %>
                <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search Articles' %>
                <span class="input-group-btn">
                <%= submit_tag "Search 2", class: 'btn btn-default' %>
              </span>
            <% end %>
          </div>

        <ul class="nav navbar-nav navbar-right">

          <li><%= link_to current_user.full_name, edit_user_path(current_user)%></li>
          <li><%= link_to "Log Out", logout_path, method: :delete%></li>
        </ul>
      <% end %>


    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->

</nav>

project3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordGram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: '/layouts/nav_bar' %>
<div class="container">
    <%= yield %>
</div>

</body>
</html>